### ISSUE TITLE
speech_iterator omits last speech in protocol

### ISSUE THREAD

**Issue by Lauler** [welfare-state-analytics/pyparlaclarin#4]
The [speech_iterator](https://github.com/welfare-state-analytics/pyparlaclarin/blob/89cb72b01033715e1dcc7411dbd970d4a197cd1b/pyparlaclarin/read.py#L85-L105) function never yields the last speech in a protocol, since the check for whether the speaker changes never triggers for the last speaker (there is no speaker after the last speaker). 

Here's my own modified iterator:

```python
def speech_iterator(root):
    """
    Convert Parla-Clarin XML to an iterator of of concatenated speeches and speaker ids.
    Speech segments are concatenated unless a new speaker appears (ignoring any notes).

    Args:
        root: Parla-Clarin document root, as an lxml tree root.
    """
    us = root.findall(".//{http://www.tei-c.org/ns/1.0}u")
    # Find all 'docDate' elements
    docdates = root.findall(".//{http://www.tei-c.org/ns/1.0}docDate")
    if len(us) == 0:
        return None

    speaker_id_old = us[0].attrib.get("who", "")
    dates = [docdate.get("when", "") for docdate in docdates]

    speech = []
    for u in us:
        speech_id = u.get("{http://www.w3.org/XML/1998/namespace}id", "")
        for text in u.itertext():
            speaker_id = u.attrib.get("who", "")
            if speaker_id != speaker_id_old:
                yield (
                    {
                        "text": " ".join(speech),
                        "speaker_id": speaker_id,
                        "speech_id": speech_id,
                        "date": dates,
                    }
                )
                speech = []
            speech.extend(text.split())
            speaker_id_old = speaker_id

    # Yield the last segment
    if speech:
        yield {
            "text": " ".join(speech),
            "speaker_id": speaker_id_old,
            "speech_id": speech_id,
            "date": dates,
        }
```

**Comment by ninpnin** [comment]
This was done before the "next" and "prev" attributes were fixed. Now you can traverse from one ```<u>``` element to the next one by finding the element by the id given in "next". See eg. [L285](https://github.com/swerik-project/riksdagen-records/blob/main/data/1967/prot-1967--ak--006.xml#L285) and [L292](https://github.com/swerik-project/riksdagen-records/blob/main/data/1967/prot-1967--ak--006.xml#L292)

Regardless, we'll fix this in the module too.

**Comment by ninpnin** [comment]
I just fixed this, works correctly on the example protocol I gave it. Published as v0.9.0 on pypi now. @Lauler if you could try and use it to double check, that would be highly appreciated.

**Comment by ninpnin** [comment]
Nevermind, there is something wrong with PyPi!

```
HTTP Error 403: New uploads are temporarily disabled. 
```

**Comment by ninpnin** [comment]
If I forget to come upload this later, feel free to remind me.

**Comment by ninpnin** [comment]
Up now https://pypi.org/project/pyparlaclarin/#history

**Comment by Lauler** [comment]
Tested it and it works well.

Thanks!

**Comment by Lauler** [comment]
After some testing I decided to use the prev and next attributes like you suggested. It was more robust, since sometimes the same speaker (usually the speaker of the house) will have two speeches after one another.
